kind = "DojoModel"
class_hash = "0x1dc8b9f85a186d551a8d53b5b46cffe82a5505fa6855c0f9af7facb6946db09"
original_class_hash = "0x1dc8b9f85a186d551a8d53b5b46cffe82a5505fa6855c0f9af7facb6946db09"
abi = "manifests/slotdev/base/abis/models/zkube-Player-a3c56d30.json"
tag = "zkube-Player"
qualified_path = "zkube::models::index::player"
manifest_name = "zkube-Player-a3c56d30"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "game_id"
type = "u32"
key = false

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "points"
type = "u32"
key = false

[[members]]
name = "daily_streak"
type = "u8"
key = false

[[members]]
name = "last_active_day"
type = "u32"
key = false

[[members]]
name = "account_creation_day"
type = "u32"
key = false
