[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/slotdev/deployment/abis/dojo-world.json"
address = "0x4a4c6cca46f2aea40f0bac6a3d16f25394cb2e9ed274b326521459e1ccab2c7"
transaction_hash = "0x6d3b8a8a270e68c870f2b59d37c59dd0d296d90f68f48de89b8af80529c5483"
block_number = 60
seed = "zKube3"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "slotdev"
rpc_url = "https://api.cartridge.gg/x/zkube-slotdev/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x38f266d807c69f8ce39f212ba67a650c18d9a2362d5437bde8fa0de02619b82"
class_hash = "0x46d81486de0a2182d0033cfae4f8113f4432168a7050d45974263b788f583a1"
original_class_hash = "0x46d81486de0a2182d0033cfae4f8113f4432168a7050d45974263b788f583a1"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-account-6d28004d.json"
reads = []
writes = [
    "zkube-Player",
    "zkube-Credits",
]
init_calldata = []
tag = "zkube-account"
systems = [
    "create",
    "rename",
]
manifest_name = "zkube-account-6d28004d"

[[contracts]]
kind = "DojoContract"
address = "0x4103e7e0add61651b2830e99b5efb843ec4c948f37db1dae9ed2c8c00a71e84"
class_hash = "0x261fb0322818d856cda306ed7479874b965b9faead1b6485f1186449d9609f6"
original_class_hash = "0x261fb0322818d856cda306ed7479874b965b9faead1b6485f1186449d9609f6"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-chest-5d3b3ea3.json"
reads = []
writes = [
    "zkube-Chest",
    "zkube-Participation",
]
init_calldata = ["0x0730b8077dc0db1ac0138b2474a85b70b833a3ad6318059f60671ebb09195e67"]
tag = "zkube-chest"
systems = [
    "claim",
    "sponsor",
    "sponsor_from",
]
manifest_name = "zkube-chest-5d3b3ea3"

[[contracts]]
kind = "DojoContract"
address = "0x5f165c5ea1ebb18e27749335ed11e691718144c59c33a6aa80700f5d5a07d40"
class_hash = "0x67f615051b3e12869e0aef779876f9a71c0a634bcf21aaeb27cc71a211ca56f"
original_class_hash = "0x67f615051b3e12869e0aef779876f9a71c0a634bcf21aaeb27cc71a211ca56f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = [
    "zkube-Player",
    "zkube-Game",
    "zkube-Tournament",
    "zkube-Credits",
    "zkube-Settings",
    "zkube-Chest",
    "zkube-Participation",
]
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"

[[contracts]]
kind = "DojoContract"
address = "0x7d59929cc73cc8e568d652b4957b5f6c98c718f6e0c5cd239069b5806a40a89"
class_hash = "0x27e87f8f3658b5b33c91d1c020177f0333bdf3532ed8f3bcdfa544166ff4dd6"
original_class_hash = "0x27e87f8f3658b5b33c91d1c020177f0333bdf3532ed8f3bcdfa544166ff4dd6"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-settings-3b7c4918.json"
reads = []
writes = [
    "zkube-Settings",
    "zkube-Admin",
]
init_calldata = ["0x01a988f1faf473743f144dd6d7c04026d363fe72e697a35292eeb18be2ca8717"]
tag = "zkube-settings"
systems = [
    "update_zkorp_address",
    "update_free_daily_credits",
    "update_daily_mode_price",
    "update_normal_mode_price",
    "set_admin",
    "delete_admin",
]
manifest_name = "zkube-settings-3b7c4918"

[[contracts]]
kind = "DojoContract"
address = "0x2f8a89a05679b616e2134032ace3532cba1c6764ccfaad3b5fec8d0d66f51da"
class_hash = "0x35a5c7a0d2348bc6eeb544fb6c679d0f1cd05ad2397d661f421ada8685fccfe"
original_class_hash = "0x35a5c7a0d2348bc6eeb544fb6c679d0f1cd05ad2397d661f421ada8685fccfe"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-tournament-2101600e.json"
reads = []
writes = ["zkube-Tournament"]
init_calldata = ["0x0730b8077dc0db1ac0138b2474a85b70b833a3ad6318059f60671ebb09195e67"]
tag = "zkube-tournament"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-tournament-2101600e"

[[contracts]]
kind = "DojoContract"
address = "0x1f110b57e55c772ba321346248b5faab3b0c5915d042a52e44acbff0aa262ec"
class_hash = "0x12b37d078e6ee707b24a3d5e32684bdd0ca0d2afbc569a5b73175b489497115"
original_class_hash = "0x12b37d078e6ee707b24a3d5e32684bdd0ca0d2afbc569a5b73175b489497115"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-zkorp-6cdc1046.json"
reads = []
writes = []
init_calldata = ["0x0730b8077dc0db1ac0138b2474a85b70b833a3ad6318059f60671ebb09195e67"]
tag = "zkube-zkorp"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-zkorp-6cdc1046"

[[models]]
kind = "DojoModel"
class_hash = "0x75ca4403fec8334e5819c3b134ab67420cf93d86b9809a7cfc2d2509530622f"
original_class_hash = "0x75ca4403fec8334e5819c3b134ab67420cf93d86b9809a7cfc2d2509530622f"
abi = "manifests/slotdev/deployment/abis/models/zkube-Admin-3feb084f.json"
tag = "zkube-Admin"
qualified_path = "zkube::models::index::admin"
manifest_name = "zkube-Admin-3feb084f"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "is_set"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4ebc00a7ff8d99ef6a898161a20ce5f8e8a5cb96f471207a2b4d8a518262c0e"
original_class_hash = "0x4ebc00a7ff8d99ef6a898161a20ce5f8e8a5cb96f471207a2b4d8a518262c0e"
abi = "manifests/slotdev/deployment/abis/models/zkube-Chest-4d11a491.json"
tag = "zkube-Chest"
qualified_path = "zkube::models::index::chest"
manifest_name = "zkube-Chest-4d11a491"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "point_target"
type = "u32"
key = false

[[models.members]]
name = "points"
type = "u32"
key = false

[[models.members]]
name = "prize"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2d07e33460dde8b110ef5359231c986a3c597a389e0da1cfead5904371da1cc"
original_class_hash = "0x2d07e33460dde8b110ef5359231c986a3c597a389e0da1cfead5904371da1cc"
abi = "manifests/slotdev/deployment/abis/models/zkube-Credits-20403c75.json"
tag = "zkube-Credits"
qualified_path = "zkube::models::index::credits"
manifest_name = "zkube-Credits-20403c75"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "day_id"
type = "u64"
key = false

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5ad70a3174e1a5fd24b713489e49b9d1b695f8901c94d24a39a7c2330569227"
original_class_hash = "0x5ad70a3174e1a5fd24b713489e49b9d1b695f8901c94d24a39a7c2330569227"
abi = "manifests/slotdev/deployment/abis/models/zkube-Game-17e542e0.json"
tag = "zkube-Game"
qualified_path = "zkube::models::index::game"
manifest_name = "zkube-Game-17e542e0"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "moves"
type = "u32"
key = false

[[models.members]]
name = "next_row"
type = "u32"
key = false

[[models.members]]
name = "next_color"
type = "u32"
key = false

[[models.members]]
name = "hammer_bonus"
type = "u8"
key = false

[[models.members]]
name = "wave_bonus"
type = "u8"
key = false

[[models.members]]
name = "totem_bonus"
type = "u8"
key = false

[[models.members]]
name = "hammer_used"
type = "u8"
key = false

[[models.members]]
name = "wave_used"
type = "u8"
key = false

[[models.members]]
name = "totem_used"
type = "u8"
key = false

[[models.members]]
name = "combo_counter"
type = "u8"
key = false

[[models.members]]
name = "max_combo"
type = "u8"
key = false

[[models.members]]
name = "blocks"
type = "felt252"
key = false

[[models.members]]
name = "colors"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "mode"
type = "u8"
key = false

[[models.members]]
name = "start_time"
type = "u64"
key = false

[[models.members]]
name = "tournament_id"
type = "u64"
key = false

[[models.members]]
name = "score_in_tournament"
type = "u32"
key = false

[[models.members]]
name = "combo_counter_in_tournament"
type = "u8"
key = false

[[models.members]]
name = "max_combo_in_tournament"
type = "u8"
key = false

[[models.members]]
name = "pending_chest_prize"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6d487a9e257063fa50bd2f6331ba3d8d82a62a4851b95802756a0b1b6f4a1de"
original_class_hash = "0x6d487a9e257063fa50bd2f6331ba3d8d82a62a4851b95802756a0b1b6f4a1de"
abi = "manifests/slotdev/deployment/abis/models/zkube-Participation-7b168a64.json"
tag = "zkube-Participation"
qualified_path = "zkube::models::index::participation"
manifest_name = "zkube-Participation-7b168a64"

[[models.members]]
name = "chest_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "is_set"
type = "bool"
key = false

[[models.members]]
name = "points"
type = "u32"
key = false

[[models.members]]
name = "claimed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xf9b6c922045b89af068513b0a9c3df3c687a437dfece00c51f7b09ee22444"
original_class_hash = "0xf9b6c922045b89af068513b0a9c3df3c687a437dfece00c51f7b09ee22444"
abi = "manifests/slotdev/deployment/abis/models/zkube-Player-a3c56d30.json"
tag = "zkube-Player"
qualified_path = "zkube::models::index::player"
manifest_name = "zkube-Player-a3c56d30"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "points"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1faf1fb96f5e756885d39feaa8b2777f21845d67c1d5e8df770372173ee62a9"
original_class_hash = "0x1faf1fb96f5e756885d39feaa8b2777f21845d67c1d5e8df770372173ee62a9"
abi = "manifests/slotdev/deployment/abis/models/zkube-Settings-161104df.json"
tag = "zkube-Settings"
qualified_path = "zkube::models::index::settings"
manifest_name = "zkube-Settings-161104df"

[[models.members]]
name = "id"
type = "u8"
key = true

[[models.members]]
name = "is_set"
type = "bool"
key = false

[[models.members]]
name = "zkorp_address"
type = "felt252"
key = false

[[models.members]]
name = "free_daily_credits"
type = "u8"
key = false

[[models.members]]
name = "daily_mode_price"
type = "u128"
key = false

[[models.members]]
name = "normal_mode_price"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xd28fd534451aca076dda7a67fee4a48f120bb478b5b27be15879ac0037f6e5"
original_class_hash = "0xd28fd534451aca076dda7a67fee4a48f120bb478b5b27be15879ac0037f6e5"
abi = "manifests/slotdev/deployment/abis/models/zkube-Tournament-120c37d1.json"
tag = "zkube-Tournament"
qualified_path = "zkube::models::index::tournament"
manifest_name = "zkube-Tournament-120c37d1"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "is_set"
type = "bool"
key = false

[[models.members]]
name = "prize"
type = "u128"
key = false

[[models.members]]
name = "top1_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top2_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top3_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top1_score"
type = "u32"
key = false

[[models.members]]
name = "top2_score"
type = "u32"
key = false

[[models.members]]
name = "top3_score"
type = "u32"
key = false

[[models.members]]
name = "top1_claimed"
type = "bool"
key = false

[[models.members]]
name = "top2_claimed"
type = "bool"
key = false

[[models.members]]
name = "top3_claimed"
type = "bool"
key = false

[[models.members]]
name = "top1_game_id"
type = "u32"
key = false

[[models.members]]
name = "top2_game_id"
type = "u32"
key = false

[[models.members]]
name = "top3_game_id"
type = "u32"
key = false
