[package]
name = "token"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.7.0"
scarb-version = "2.7.0"

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.7.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.1" }

[dev-dependencies]
