[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/slotdev/deployment/abis/dojo-world.json"
address = "0x5ef8195dbf43ea66b14d7bfec4ed6b565386a49dff34aa474c3cd29aa0fa615"
transaction_hash = "0x1e00e184dfd939745424d2e91d460b431220db250a328f66cfbebd092e3814c"
block_number = 3
seed = "zKube"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "slotdev"
rpc_url = "https://api.cartridge.gg/x/zkube-slotdev/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x7362142438f82017175c44aff9ef6a1887824d57843e42a094d765bfbc0adf8"
class_hash = "0x13b2fca532997e789de9e51aad67d530ea6300976b03617831443e95fff40c0"
original_class_hash = "0x13b2fca532997e789de9e51aad67d530ea6300976b03617831443e95fff40c0"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-account-6d28004d.json"
reads = []
writes = [
    "zkube-Player",
    "zkube-Game",
    "zkube-Tournament",
    "zkube-Credits",
]
init_calldata = []
tag = "zkube-account"
systems = [
    "create",
    "rename",
]
manifest_name = "zkube-account-6d28004d"

[[contracts]]
kind = "DojoContract"
address = "0x8fbe72f6d350f76cfd6554872befc4d61889d4029a66cf3897506a908f77ca"
class_hash = "0x48e480a0494db904cd6f64b787824c6a33eaf12c6bb264d8351934b0a26b1ae"
original_class_hash = "0x48e480a0494db904cd6f64b787824c6a33eaf12c6bb264d8351934b0a26b1ae"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/slotdev/deployment/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = [
    "zkube-Player",
    "zkube-Game",
    "zkube-Tournament",
    "zkube-Credits",
]
init_calldata = ["0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"]
tag = "zkube-play"
systems = [
    "claim",
    "sponsor",
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"

[[models]]
kind = "DojoModel"
class_hash = "0x2d07e33460dde8b110ef5359231c986a3c597a389e0da1cfead5904371da1cc"
original_class_hash = "0x2d07e33460dde8b110ef5359231c986a3c597a389e0da1cfead5904371da1cc"
abi = "manifests/slotdev/deployment/abis/models/zkube-Credits-20403c75.json"
tag = "zkube-Credits"
qualified_path = "zkube::models::index::credits"
manifest_name = "zkube-Credits-20403c75"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "day_id"
type = "u64"
key = false

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5e1d8bd1fc67cef0ef1b9e642a44c13474d93cd5123e2b233cdbac9dc79de0c"
original_class_hash = "0x5e1d8bd1fc67cef0ef1b9e642a44c13474d93cd5123e2b233cdbac9dc79de0c"
abi = "manifests/slotdev/deployment/abis/models/zkube-Game-17e542e0.json"
tag = "zkube-Game"
qualified_path = "zkube::models::index::game"
manifest_name = "zkube-Game-17e542e0"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "moves"
type = "u32"
key = false

[[models.members]]
name = "next_row"
type = "u32"
key = false

[[models.members]]
name = "next_color"
type = "u32"
key = false

[[models.members]]
name = "hammer_bonus"
type = "u8"
key = false

[[models.members]]
name = "wave_bonus"
type = "u8"
key = false

[[models.members]]
name = "totem_bonus"
type = "u8"
key = false

[[models.members]]
name = "hammer_used"
type = "u8"
key = false

[[models.members]]
name = "wave_used"
type = "u8"
key = false

[[models.members]]
name = "totem_used"
type = "u8"
key = false

[[models.members]]
name = "combo_counter"
type = "u8"
key = false

[[models.members]]
name = "max_combo"
type = "u8"
key = false

[[models.members]]
name = "blocks"
type = "felt252"
key = false

[[models.members]]
name = "colors"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "mode"
type = "u8"
key = false

[[models.members]]
name = "start_time"
type = "u64"
key = false

[[models.members]]
name = "tournament_id"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xf9b6c922045b89af068513b0a9c3df3c687a437dfece00c51f7b09ee22444"
original_class_hash = "0xf9b6c922045b89af068513b0a9c3df3c687a437dfece00c51f7b09ee22444"
abi = "manifests/slotdev/deployment/abis/models/zkube-Player-a3c56d30.json"
tag = "zkube-Player"
qualified_path = "zkube::models::index::player"
manifest_name = "zkube-Player-a3c56d30"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "points"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x40192a8af7bea738cee0feffb7de37f6b15e21f6809cff453268e65f240d1b6"
original_class_hash = "0x40192a8af7bea738cee0feffb7de37f6b15e21f6809cff453268e65f240d1b6"
abi = "manifests/slotdev/deployment/abis/models/zkube-Tournament-120c37d1.json"
tag = "zkube-Tournament"
qualified_path = "zkube::models::index::tournament"
manifest_name = "zkube-Tournament-120c37d1"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "prize"
type = "felt252"
key = false

[[models.members]]
name = "top1_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top2_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top3_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top1_score"
type = "u32"
key = false

[[models.members]]
name = "top2_score"
type = "u32"
key = false

[[models.members]]
name = "top3_score"
type = "u32"
key = false

[[models.members]]
name = "top1_claimed"
type = "bool"
key = false

[[models.members]]
name = "top2_claimed"
type = "bool"
key = false

[[models.members]]
name = "top3_claimed"
type = "bool"
key = false
