kind = "DojoModel"
class_hash = "0x7df0095dee0c2eb9301e469f9f8268b4eadbd0c0c6ee21d29bee1cc6a35136f"
original_class_hash = "0x7df0095dee0c2eb9301e469f9f8268b4eadbd0c0c6ee21d29bee1cc6a35136f"
abi = "manifests/sepoliadev1/base/abis/models/zkube-Game-17e542e0.json"
tag = "zkube-Game"
qualified_path = "zkube::models::index::game"
manifest_name = "zkube-Game-17e542e0"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "moves"
type = "u32"
key = false

[[members]]
name = "next_row"
type = "u32"
key = false

[[members]]
name = "hammer_bonus"
type = "u8"
key = false

[[members]]
name = "wave_bonus"
type = "u8"
key = false

[[members]]
name = "totem_bonus"
type = "u8"
key = false

[[members]]
name = "hammer_used"
type = "u8"
key = false

[[members]]
name = "wave_used"
type = "u8"
key = false

[[members]]
name = "totem_used"
type = "u8"
key = false

[[members]]
name = "combo_counter"
type = "u8"
key = false

[[members]]
name = "max_combo"
type = "u8"
key = false

[[members]]
name = "blocks"
type = "felt252"
key = false

[[members]]
name = "player_id"
type = "felt252"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "mode"
type = "u8"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false

[[members]]
name = "tournament_id"
type = "u64"
key = false

[[members]]
name = "score_in_tournament"
type = "u32"
key = false

[[members]]
name = "combo_counter_in_tournament"
type = "u8"
key = false

[[members]]
name = "max_combo_in_tournament"
type = "u8"
key = false

[[members]]
name = "pending_chest_prize"
type = "u128"
key = false
