[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/sepolia/abis/deployments/dojo_world_world.json"
address = "0x491ad6881ccae1882d70b708e220f6d59e37589611bb8860906833ec67d099"
transaction_hash = "0x20622f72645e4a51c839ab8fd61096caef55dd5e5f9994e9ede4e102bcbdba1"
seed = "zkube-v2"
name = "dojo::world::world"

[world.metadata]
profile_name = "sepolia"
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x2c43187941a28e669cca7332d27d66c889992c0f8cc7dce3a1e4e1430ba1114"
class_hash = "0x4ed9f1af618a5bd13a0c7d7a64bc5bfef583c83bd97d1696315419a3b373851"
original_class_hash = "0x4ed9f1af618a5bd13a0c7d7a64bc5bfef583c83bd97d1696315419a3b373851"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/sepolia/abis/deployments/contracts/zkube_systems_actions_actions.json"
reads = []
writes = [
    "Player",
    "Game",
]
computed = []
init_calldata = []
name = "zkube::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x7f9ef38357da1be1090e5c94c8e3edd015252e1465b76bff44de696c17e722d"
original_class_hash = "0x7f9ef38357da1be1090e5c94c8e3edd015252e1465b76bff44de696c17e722d"
abi = "manifests/sepolia/abis/deployments/models/zkube_models_index_game.json"
name = "zkube::models::index::game"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "next_row"
type = "u32"
key = false

[[models.members]]
name = "next_color"
type = "u32"
key = false

[[models.members]]
name = "hammer_bonus"
type = "u8"
key = false

[[models.members]]
name = "wave_bonus"
type = "u8"
key = false

[[models.members]]
name = "totem_bonus"
type = "u8"
key = false

[[models.members]]
name = "combo_counter"
type = "u8"
key = false

[[models.members]]
name = "blocks"
type = "felt252"
key = false

[[models.members]]
name = "colors"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5fed3730bb3d7d98cc66dfe1c18a3a06b2af4db5fdaa2f4aada377fc550d74"
original_class_hash = "0x5fed3730bb3d7d98cc66dfe1c18a3a06b2af4db5fdaa2f4aada377fc550d74"
abi = "manifests/sepolia/abis/deployments/models/zkube_models_index_player.json"
name = "zkube::models::index::player"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "game_id"
type = "u32"
key = false

[[models.members]]
name = "hammer_bonus"
type = "u8"
key = false

[[models.members]]
name = "wave_bonus"
type = "u8"
key = false

[[models.members]]
name = "totem_bonus"
type = "u8"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "points"
type = "u32"
key = false
