kind = "DojoContract"
class_hash = "0x7ece8a86dff2ae5211439a9b9815f1c33fddb124db613da204e63fc814ffab1"
original_class_hash = "0x7ece8a86dff2ae5211439a9b9815f1c33fddb124db613da204e63fc814ffab1"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zkube-tournament-2101600e.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-tournament"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-tournament-2101600e"
