kind = "DojoModel"
class_hash = "0x5e1d8bd1fc67cef0ef1b9e642a44c13474d93cd5123e2b233cdbac9dc79de0c"
original_class_hash = "0x5e1d8bd1fc67cef0ef1b9e642a44c13474d93cd5123e2b233cdbac9dc79de0c"
abi = "manifests/dev/base/abis/models/zkube-Game-17e542e0.json"
tag = "zkube-Game"
manifest_name = "zkube-Game-17e542e0"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "moves"
type = "u32"
key = false

[[members]]
name = "next_row"
type = "u32"
key = false

[[members]]
name = "next_color"
type = "u32"
key = false

[[members]]
name = "hammer_bonus"
type = "u8"
key = false

[[members]]
name = "wave_bonus"
type = "u8"
key = false

[[members]]
name = "totem_bonus"
type = "u8"
key = false

[[members]]
name = "hammer_used"
type = "u8"
key = false

[[members]]
name = "wave_used"
type = "u8"
key = false

[[members]]
name = "totem_used"
type = "u8"
key = false

[[members]]
name = "combo_counter"
type = "u8"
key = false

[[members]]
name = "max_combo"
type = "u8"
key = false

[[members]]
name = "blocks"
type = "felt252"
key = false

[[members]]
name = "colors"
type = "felt252"
key = false

[[members]]
name = "player_id"
type = "felt252"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "mode"
type = "u8"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false

[[members]]
name = "tournament_id"
type = "u64"
key = false
