[world]
name = "zKube"
description = "Reversed tetris fully onchain."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "zKube6"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "zkube"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x0601ecb93c6e88eec432910a2c3ab4d9b5c0dd768b55ab4f8c89336e01fafaa7"
private_key = "0x9a2816a70849c36ce6ef74a8b5d8007e40f36f3e96d1ce72d2bced106e8b1f"

[init_call_args]
"zkube-chest" = ["0x021d1aa0b2c3413f0b8a1c14ddcdbaf404debfb0d4d858d0bb6ccb48ec1c0c51"]
"zkube-settings" = ["0x0589d37adc1e5cf9ef58da510ee904aa9428d6e9a1c0d5c822392664d063796b"]
"zkube-tournament" = ["0x021d1aa0b2c3413f0b8a1c14ddcdbaf404debfb0d4d858d0bb6ccb48ec1c0c51"]
"zkube-zkorp" = ["0x021d1aa0b2c3413f0b8a1c14ddcdbaf404debfb0d4d858d0bb6ccb48ec1c0c51"]

[writers]
"zkube-Admin" = ["zkube-settings"]
"zkube-Chest" = ["zkube-chest", "zkube-play"]
"zkube-Game" = ["zkube-play"]
"zkube-Mint" = ["zkube-minter"]
"zkube-Participation" = ["zkube-chest", "zkube-play"]
"zkube-Player" = ["zkube-account", "zkube-play"]
"zkube-Settings" = ["zkube-settings"]
"zkube-Tournament" = ["zkube-play", "zkube-tournament"]