[world]
name = "zKube"
description = "Reversed tetris fully onchain."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://app.zkube.xyz"
seed = "zkube0"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "zkube_budo_v1_1_0"

[env]
rpc_url = "https://api.cartridge.gg/x/zkube-cheelax/katana"
account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"
world_address = "0x079a36feddf1856076a253d9f6f268ee977f52e8f18b4729a64d63bdaab93331"

[writers]
"zkube_budo_v1_1_0-Game" = ["zkube_budo_v1_1_0-game_system"]
"zkube_budo_v1_1_0-GameSeed" = ["zkube_budo_v1_1_0-game_system"]
"zkube_budo_v1_1_0-GameCounter" = ["zkube_budo_v1_1_0-game_system"]
"zkube_budo_v1_1_0-GameMetadata" = ["zkube_budo_v1_1_0-game_system"]
"zkube_budo_v1_1_0-TokenMetadata" = ["zkube_budo_v1_1_0-game_system"]
"zkube_budo_v1_1_0-GameSettings" = ["zkube_budo_v1_1_0-config_system"]
"zkube_budo_v1_1_0-GameSettingsMetadata" = ["zkube_budo_v1_1_0-config_system"]
"zkube_budo_v1_1_0-TrophyCreation" = ["zkube_budo_v1_1_0-achievement_system"]
"zkube_budo_v1_1_0-TrophyProgression" = ["zkube_budo_v1_1_0-achievement_system"]

[init_call_args]
"zkube_budo_v1_1_0-game_system" = [
    "0x6daf2a924fab727ae5409f0743de4869850f988b6f8545268016ad1107fd2cd",
]
"zkube_budo_v1_1_0-config_system" = [
    "0x6daf2a924fab727ae5409f0743de4869850f988b6f8545268016ad1107fd2cd",
]