[world]
name = "zKube"
description = "Reversed tetris fully onchain."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "zKube18"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "zkube"

[env]
rpc_url = "https://api.cartridge.gg/x/zkube-slotdev/katana"
account_address = "0x7b2ad9c0a331a84015dc07f71dd3d54545bac6f09b5385aa171db29fc32fbb6"
private_key = "0x562b095dfdef600413f27b79a3fd908957b9449bd0c9e0fbdfb68594d6fa1f6"

[init_call_args]
"zkube-chest" = ["0x00020d7b2b056f5e0d8d413088460579fc5465f5dc694c08ada638344573cea2"]
"zkube-settings" = ["0x7b2ad9c0a331a84015dc07f71dd3d54545bac6f09b5385aa171db29fc32fbb6", "0x7b2ad9c0a331a84015dc07f71dd3d54545bac6f09b5385aa171db29fc32fbb6"]
"zkube-tournament" = ["0x00020d7b2b056f5e0d8d413088460579fc5465f5dc694c08ada638344573cea2"]
"zkube-zkorp" = ["0x00020d7b2b056f5e0d8d413088460579fc5465f5dc694c08ada638344573cea2"]

[writers]
"zkube-Admin" = ["zkube-settings"]
"zkube-Chest" = ["zkube-chest", "zkube-play"]
"zkube-Game" = ["zkube-play"]
"zkube-Mint" = ["zkube-minter"]
"zkube-Participation" = ["zkube-chest", "zkube-play"]
"zkube-Player" = ["zkube-account", "zkube-play"]
"zkube-Settings" = ["zkube-minter", "zkube-settings"]
"zkube-Tournament" = ["zkube-play", "zkube-tournament"]