kind = "DojoModel"
class_hash = "0x5fed3730bb3d7d98cc66dfe1c18a3a06b2af4db5fdaa2f4aada377fc550d74"
original_class_hash = "0x5fed3730bb3d7d98cc66dfe1c18a3a06b2af4db5fdaa2f4aada377fc550d74"
abi = "manifests/slot/abis/base/models/zkube_models_index_player.json"
name = "zkube::models::index::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "game_id"
type = "u32"
key = false

[[members]]
name = "hammer_bonus"
type = "u8"
key = false

[[members]]
name = "wave_bonus"
type = "u8"
key = false

[[members]]
name = "totem_bonus"
type = "u8"
key = false

[[members]]
name = "name"
type = "felt252"
key = false
