kind = "DojoContract"
class_hash = "0x754255d4521a1674abe2549c351e732ebf48896aef6922a8e939f3a574982c7"
original_class_hash = "0x754255d4521a1674abe2549c351e732ebf48896aef6922a8e939f3a574982c7"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/zkube-tournament-2101600e.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-tournament"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-tournament-2101600e"
