kind = "DojoContract"
class_hash = "0x5cbc5e731107f9ac652676ccba05b93903fa2571809d46c5a453193c4a42b32"
original_class_hash = "0x5cbc5e731107f9ac652676ccba05b93903fa2571809d46c5a453193c4a42b32"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
