kind = "DojoContract"
class_hash = "0x4ed9f1af618a5bd13a0c7d7a64bc5bfef583c83bd97d1696315419a3b373851"
original_class_hash = "0x4ed9f1af618a5bd13a0c7d7a64bc5bfef583c83bd97d1696315419a3b373851"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/zkube_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "zkube::systems::actions::actions"
